In [1]:
from activation_functions_no_builder import *

In [2]:
relu = RELU(
    batch_size=5,
    vector_size=3
)

In [3]:
X = np.random.uniform(-5, 5, size=(3,5))

In [4]:
relu.compute_activation(X)

array([[-0.        ,  2.61536437,  1.80511058, -0.        , -0.        ],
       [-0.        ,  0.62441146, -0.        , -0.        ,  2.79951847],
       [ 0.61625504,  0.08688536,  0.71669391,  3.86001165, -0.        ]])

In [5]:
relu.compute_activation_gradient()

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]]])

In [6]:
relu.compute_activation_gradient()

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]]])

In [7]:
non_activation = Identity_Function(
    batch_size=5,
    vector_size=3
)

In [8]:
X = np.random.uniform(-1, 1, (3,5))
X

array([[-0.52268928,  0.09238397, -0.59046745, -0.93742159,  0.50546806],
       [-0.76651195,  0.37257501,  0.52212052,  0.96230053, -0.57359752],
       [-0.29012288, -0.29400131,  0.99833339, -0.19669837,  0.00213355]])

In [9]:
non_activation.compute_activation(X)

array([[-0.52268928,  0.09238397, -0.59046745, -0.93742159,  0.50546806],
       [-0.76651195,  0.37257501,  0.52212052,  0.96230053, -0.57359752],
       [-0.29012288, -0.29400131,  0.99833339, -0.19669837,  0.00213355]])

In [10]:
non_activation.compute_activation_gradient(X)

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])