In [1]:
from layer_no_builder import *
from activation_functions_no_builder import *
from loss_functions_no_builder import *

In [2]:
dropout = Dropout_Layer(
    dropout_rate=0.4,
    input_size=5,
    batch_size=5
)

In [3]:
X = np.random.uniform(-1, 1, (5, 5))

In [4]:
dropout.foreward_propagate(X)

array([[ 0.37001846,  0.85829505,  0.2978707 , -0.89282427,  0.3234147 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.46658174, -0.17153959,  0.97117737,  0.14618221, -0.16652854],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.95436076, -0.47040459,  0.31758963, -0.44630288, -0.96960043]])

In [5]:
dropout.back_propagate(np.ones((5,)))

array([1., 1., 1., 1., 1.])

In [6]:
batch_size = 20

linear_regression_model = Fully_Connected_Neuron_Layer(
    input_size=1,
    output_size=1,
    activation_function=Identity_Function(batch_size=batch_size, vector_size=1),
    batch_size=batch_size
)
loss_function = MSE(batch_size=batch_size, vector_size=1)

In [7]:
# numpy supports broardcasting for simple functions
def target_function(X):
    return 3*X-5

In [8]:
# x_range = (-10, 10)
# learning_rate = 2**-6

# linear_regression_model.initialise_random_parameters()

# for i in range(10000):
#     X = np.random.uniform(low=x_range[0], high=x_range[1], size=(1, batch_size))
#     Y = target_function(X)
#     P = linear_regression_model.foreward_propagate(X)


#     loss = loss_function.compute_loss(P, Y)
#     dldP = loss_function.compute_loss_gradient()

#     linear_regression_model.back_propagate(dldP)
#     linear_regression_model.update_parameters(learning_rate)

#     if i==0 or (i+1) % 1000 == 0:
#         print(f"iteration {i}: loss was {loss:.8f}")
#         linear_regression_model.print_parameters()

In [9]:
batch_size = 50
input_size = 3
output_size = 2

target_layer = Fully_Connected_Neuron_Layer(
    input_size=input_size,
    output_size=output_size,
    activation_function=RELU(
        batch_size=batch_size,
        vector_size=output_size
    ),
    batch_size=batch_size
)
training_layer = Fully_Connected_Neuron_Layer(
    input_size=input_size,
    output_size=output_size,
    activation_function=RELU(
        batch_size=batch_size,
        vector_size=output_size
    ),
    batch_size=batch_size
)

loss_function = MSE(
    batch_size=batch_size,
    vector_size=output_size
)

In [10]:
x_range = (-5, 5)
learning_rate = 2**-6
target_bias_range = (-0.5, 0.5)
target_weight_range = (-3, 3)

training_layer.initialise_random_parameters()
target_layer.initialise_random_parameters(
    bias_range=target_bias_range,
    weight_range=target_weight_range
)

target_parameters = target_layer.get_parameters()

for i in range(10**5):
    X = np.random.uniform(low=x_range[0], high=x_range[1], size=(input_size, batch_size))
    Y = target_layer.foreward_propagate(X)
    P = training_layer.foreward_propagate(X)

    loss = loss_function.compute_loss(P, Y)
    dldP = loss_function.compute_loss_gradient()

    training_layer.back_propagate(dldP)
    training_layer.update_parameters(learning_rate)

    if i==0 or (i+1) % 10**4 == 0:
        print(f"iteration {i}: loss was {loss:.8f}")
        training_parameters = training_layer.get_parameters()
        print("Weights error:")
        print(
            training_parameters["W"] - target_parameters["W"]
        )
        print("Bias error:")
        print(
            training_parameters["B"] - target_parameters["B"]
        )

iteration 0: loss was 127.21357939
Weights error:
[[-2.66178441 -2.47883015  0.50535202]
 [ 2.07797698  1.97495475  2.92774632]]
Bias error:
[-0.03095982 -0.03191418]
iteration 9999: loss was 0.04699409
Weights error:
[[-0.06981265 -0.02004332  0.02074537]
 [ 0.03649336  0.01593898  0.02733349]]
Bias error:
[0.31419604 0.29327876]
iteration 19999: loss was 0.01187942
Weights error:
[[-0.04617233 -0.02898415  0.01486457]
 [ 0.02762894  0.02661421  0.03550363]]
Bias error:
[0.18167044 0.16296107]
iteration 29999: loss was 0.00428803
Weights error:
[[-0.02818211 -0.01354633  0.0027573 ]
 [ 0.01674435  0.02094584  0.01479872]]
Bias error:
[0.11110508 0.09254198]
iteration 39999: loss was 0.00159046
Weights error:
[[-0.01857873 -0.0066604  -0.00120781]
 [ 0.0006772   0.00836235  0.01515734]]
Bias error:
[0.06988443 0.05153776]
iteration 49999: loss was 0.00053388
Weights error:
[[-0.01205841 -0.00637869 -0.00029578]
 [ 0.00672747  0.00733245  0.00455032]]
Bias error:
[0.04694786 0.02906805]