In [1]:
from machine_learning_functions import *

In [8]:
try:   
    assert False, "msg"
except AssertionError as error:
    raise ValueError(str(error))

ValueError: msg

In [4]:
def experiment_linear(a, b, learning_rate, epochs, random_x_function):
    a, b = float(a), float(b)
    model = Model(
        FFN = FFN(
            neurons_per_layer_list=[1, 1],
            activation_functions_list=[None,],
            cost_function=MSE()
        ),
        data_set=create_1_input_1_output_XY_data(
            function=lambda x: a*x+b,
            num_data_items=10000,
            random_x_function=random_x_function
        )
    )
    print(
        model.train_and_evaluate(
            learning_rate=learning_rate,
            epochs=epochs,
            batch_size=50
        )
    )
    model.print_FFN_parameters()
    return model

In [6]:
model = experiment_linear(
    a=2, b=5,
    learning_rate=0.00025,
    epochs=1,
    random_x_function= lambda: random.uniform(-100, 100)
)
model.FFN.tranformation_layers[0].weights.dtype

(21.3454177603051, 113.76130194678558)
Parameters of network
{'W1': array([[2.02041702]])}
{'B1': array([0.52250522])}


dtype('float64')

In [4]:
experiment_linear(
    a=2, b=5,
    learning_rate=0.00025,
    epochs=1,
    random_x_function= lambda: random.uniform(-100, 100)
)

(30.39501657132671, 927.1757343554814)
Parameters of network
{'W1': array([[2.0562532]])}
{'B1': array([0.53572177])}


In [5]:
experiment_linear(
    a=1/2, b=-7,
    learning_rate=0.00025,
    epochs=1,
    random_x_function= lambda: random.uniform(-10, 10)
)

(55.766794676885354, 38.351180903069235)
Parameters of network
{'W1': array([[0.57050946]])}
{'B1': array([0.44124636])}


In [6]:
experiment_linear(
    a=1/2, b=-7,
    learning_rate=0.00025,
    epochs=5,
    random_x_function= lambda: random.uniform(-10, 10)
)

(44.86322336570385, 16.632833989096753)
Parameters of network
{'W1': array([[0.55188239]])}
{'B1': array([-0.33177718])}


In [7]:
# greater learning rate caused divergance
experiment_linear(
    a=-3, b=-1/4,
    learning_rate=0.00025,
    epochs=20,
    random_x_function= lambda: random.uniform(-10, 10)
)

KeyboardInterrupt: 

In [ ]:
experiment_linear(
    a=-3, b=-1/4,
    learning_rate=0.00025,
    epochs=50,
    random_x_function= lambda: random.uniform(-10, 10)
)

1.153899693613739e-09
Parameters of network
{'W1': array([[-3.00000003]])}
{'B1': array([-0.24996604])}


In [ ]:
def experiment_boolean_logic(input_neurons, output_neurons, function, learning_rate, epochs, hidden_layers, neurons_per_hidden_layer):
    neurons_per_layer_list = [input_neurons] + [neurons_per_hidden_layer]*hidden_layers + [output_neurons]
    activation_functions_list = [RELU() for _ in range(hidden_layers)] + [Sigmoid()]
    model = Model(
        FFN = FFN(
            neurons_per_layer_list=neurons_per_layer_list,
            activation_functions_list=activation_functions_list,
            cost_function=MSE()
        ),
        data_set=create_a_inputs_b_outputs_XY_data(
            a=input_neurons,
            b=output_neurons,
            function=function,
            random_x_function= lambda: random.choice([0.0, 1.0]),
            num_data_items=10000
        )
    )
    print(
        model.train_and_evaluate(
            learning_rate=learning_rate,
            epochs=epochs,
            batch_size=50
        )
    )
    model.print_FFN_parameters()
    return model

In [ ]:
def logical_and(X):
    a, b = bool(X[0]), int(X[1])
    return float(
        a and b
    )

experiment_boolean_logic(
    input_neurons = 2,
    output_neurons = 1,
    function=logical_and,
    learning_rate=10**-4,
    epochs=10,
    hidden_layers=2,
    neurons_per_hidden_layer=4
)

0.12960848961263577
Parameters of network
{'W1': array([[-0.65294285,  0.61589101],
       [-0.42820191,  0.95443661],
       [ 0.78559784, -0.6332115 ],
       [-0.49309623,  0.0098737 ]])}
{'B1': array([0.50288722, 0.49578408, 0.50147239, 0.50223506])}
{'W2': array([[-0.28502613,  0.84517966, -0.02225392, -0.51014619],
       [ 0.41362951,  0.76604725,  0.17653435, -0.83507039],
       [-0.73251695,  0.22706445,  0.14197284,  0.32888372],
       [ 0.33971928, -0.36906122,  0.70390109,  0.38498229]])}
{'B2': array([0.499599  , 0.49750374, 0.49630429, 0.50301195])}
{'W3': array([[-0.08625152, -0.55111397, -0.82001057,  0.67107456]])}
{'B3': array([0.50449989])}


In [ ]:
def logical_and(X):
    a, b = bool(X[0]), int(X[1])
    return np.array([float(a and b)])

and_model = experiment_boolean_logic(
    input_neurons = 2,
    output_neurons = 1,
    function=logical_and,
    learning_rate=10**-2,
    epochs=10,
    hidden_layers=2,
    neurons_per_hidden_layer=4
)

0.22791140785530437
Parameters of network
{'W1': array([[ 0.71236726,  0.92403822],
       [-0.04563622,  0.82902018],
       [-0.957013  , -0.41655979],
       [ 0.366711  , -0.79908891]])}
{'B1': array([0.58150379, 0.38601112, 0.50171204, 0.48146798])}
{'W2': array([[ 0.61075504, -0.77864653,  0.59993966, -0.49881914],
       [ 0.73361503,  0.61780799, -0.86412893, -0.15360232],
       [ 0.38080145, -0.46465994,  0.07840686,  0.23716035],
       [ 0.95144912, -0.73341645, -0.65706865,  0.1223274 ]])}
{'B2': array([0.55125803, 0.48178318, 0.47786995, 0.58917505])}
{'W3': array([[ 0.5281708 , -0.02111933, -0.17516291,  0.94342531]])}
{'B3': array([0.60308173])}


In [ ]:
(
    and_model.FFN.foreward_propagate(np.array([.0, 0.0])),
    and_model.FFN.foreward_propagate(np.array([0.0, 1.0])),
    and_model.FFN.foreward_propagate(np.array([1.0, 0.0])),
    and_model.FFN.foreward_propagate(np.array([1.0, 1.0])),
)

((array([0.02659525]), None),
 (array([0.02199461]), None),
 (array([0.01794683]), None),
 (array([0.01604408]), None))

In [ ]:
def half_adder(X):
    a, b = bool(X[0]), bool(X[1])
    sum = a ^ b
    carry = a and b
    return np.array([float(sum), float(carry)])
experiment_boolean_logic(
    input_neurons = 2,
    output_neurons = 2,
    function=half_adder,
    learning_rate=10**-4,
    epochs=10,
    hidden_layers=2,
    neurons_per_hidden_layer=4
)

0.3135790065347722
Parameters of network
{'W1': array([[ 0.80417935, -0.26562906],
       [-0.87725767, -0.12092512],
       [-0.78320205, -0.27136584],
       [ 0.35091593,  0.26535257]])}
{'B1': array([0.50024658, 0.50157549, 0.49893939, 0.49868099])}
{'W2': array([[-0.0098028 ,  0.49366171,  0.45025614, -0.34743505],
       [-0.233186  , -0.22733595,  0.75709782,  0.64877799],
       [-0.22303459, -0.92618616,  0.69403422,  0.5781448 ],
       [-0.31351791,  0.18043455,  0.31068989,  0.77025649]])}
{'B2': array([0.50153271, 0.49843039, 0.49935668, 0.50078602])}
{'W3': array([[ 0.70884425, -0.92781434, -0.21895813,  0.07905441],
       [ 0.68910313, -0.41105522, -0.40206512,  0.76649372]])}
{'B3': array([0.50129485, 0.50089337])}


In [ ]:
def half_adder_bool(A, B):
    return A ^ B, A and B

def full_adder_bool(A, B, Cin):
    S1, C1 = half_adder_bool(A, B)
    S2, C2 = half_adder_bool(S1, Cin)
    sum = S2
    carry = C1 or C2
    return sum, carry

In [ ]:
def chain_adder_bool(A_sequence, B_sequence):
    carry_out = 0
    sum_sequence = [None for _ in range(16)]
    for i in range(16):
        sum_sequence[i], carry_out = full_adder_bool(A_sequence[i], B_sequence[i], carry_out)
    return sum_sequence

In [ ]:
def full_adder_float(X):
    a, b, c_in = [bool(e) for e in X]
    s, c_out = full_adder_bool(a, b, c_in)
    return np.array([float(s), float(c_out)])

experiment_boolean_logic(
    input_neurons = 3,
    output_neurons = 2,
    function=full_adder_float,
    learning_rate=10**-4,
    epochs=10,
    hidden_layers=2,
    neurons_per_hidden_layer=4
)

0.42989678126870745
Parameters of network
{'W1': array([[-0.13046729,  0.03398441, -0.1298488 ],
       [-0.72423869,  0.78047567, -0.64296893],
       [ 0.6843604 , -0.26595864, -0.22207009],
       [-0.41476843, -0.50194339, -0.78647592]])}
{'B1': array([0.500551  , 0.50042498, 0.49871512, 0.49978004])}
{'W2': array([[-0.65096664, -0.37460568, -0.37066503,  0.75567564],
       [-0.83865972, -0.79582755,  0.49221667, -0.5953249 ],
       [-0.69872521, -0.02073121, -0.10209797,  0.1742665 ],
       [-0.587185  , -0.68434492,  0.86805485,  0.01652106]])}
{'B2': array([0.50025891, 0.49912558, 0.50068528, 0.49920759])}
{'W3': array([[ 0.44302166,  0.35661684,  0.8725924 ,  0.55579853],
       [-0.00385711, -0.42774771, -0.12385615, -0.46034002]])}
{'B3': array([0.50123403, 0.50315067])}


In [ ]:
def nibble_chain_adder_float(X):
    X = [bool(e) for e in X]
    As, Bs = X[:16], X[16:]
    S = chain_adder_bool(As, Bs)
    S = np.array([float(e) for e in S])
    return S

experiment_boolean_logic(
    input_neurons = 32,
    output_neurons = 16,
    function=nibble_chain_adder_float,
    learning_rate=10**-4,
    epochs=50,
    hidden_layers=4,
    neurons_per_hidden_layer=16
)

1.191507532951934
Parameters of network
{'W1': array([[ 6.11125611e-01,  1.14858367e-01, -4.95287944e-01,
        -6.25415027e-01, -2.53345060e-01, -7.54530891e-01,
        -2.92707485e-01,  7.76460302e-01,  5.63399112e-03,
        -7.48106081e-01,  5.69085296e-02,  5.47629344e-01,
        -6.48915951e-01, -3.63134604e-01, -9.06494622e-01,
         1.13467815e-02, -2.61377319e-01,  3.04120455e-01,
         3.08378312e-01,  6.46972992e-02, -4.59864541e-01,
         5.67630634e-01,  9.18967193e-01, -9.82585472e-01,
        -4.20437556e-01, -6.64320203e-02, -6.49667910e-01,
         4.38514490e-01,  9.86187351e-01, -3.54789901e-02,
         6.41888373e-01,  9.04014896e-01],
       [ 8.45828349e-02,  1.01889100e+00,  7.53080810e-01,
         1.55303544e-02,  3.13309410e-02,  7.60985437e-01,
        -4.85823744e-01, -2.66594230e-01,  8.18592904e-01,
         2.22874715e-01, -9.39888359e-01, -7.29218120e-02,
        -4.90382179e-01, -3.78657325e-01, -3.74402574e-01,
         6.30120738e-01, 

In [ ]:
def complex_mathematical_function_experiment(function, epochs, learning_rate, hidden_layers, neurons_per_hidden_layer, input_neurons, output_neurons, random_x_generator):
    neurons_per_layer_list = [input_neurons] + [neurons_per_hidden_layer]*hidden_layers + [output_neurons]
    activation_functions_list = [Sigmoid() for _ in range(hidden_layers)] + [None]
    model = Model(
        FFN = FFN(
            neurons_per_layer_list=neurons_per_layer_list,
            activation_functions_list=activation_functions_list,
            cost_function=MSE()
        ),
        data_set=create_a_inputs_b_outputs_XY_data(
            a=input_neurons,
            b=output_neurons,
            function=function,
            random_x_function=random_x_generator,
            num_data_items=10000
        )
    )
    print(
        model.train_and_evaluate(
            learning_rate=learning_rate,
            epochs=epochs,
            batch_size=50
        )
    )
    model.print_FFN_parameters()
    return model

In [ ]:
def pythagerous_function(X):
    a, b = X
    c = (a**2 + b**2)**1/2
    return np.array([c])

complex_mathematical_function_experiment(
    function=pythagerous_function,
    input_neurons=2,
    output_neurons=1,
    random_x_generator=lambda: random.uniform(-10, 10),
    hidden_layers=4,
    neurons_per_hidden_layer=10,
    epochs=20,
    learning_rate=10**-4
)

826.1524059854028
Parameters of network
{'W1': array([[ 0.56304594, -0.70286613],
       [-4.45720007,  5.76080034],
       [-0.14882578,  0.78182942],
       [-0.42953618,  0.09620127],
       [ 0.06753011, -0.8559187 ],
       [ 0.44008997,  2.02998988],
       [ 0.20274   , -1.11975257],
       [ 1.1316689 , -0.21597949],
       [-0.47337577, -0.38376731],
       [ 0.26034373, -0.74415172]])}
{'B1': array([0.46792926, 1.86286723, 0.49587635, 0.45561988, 0.38114442,
       0.70457421, 0.47414505, 0.39452113, 0.52001625, 0.47902841])}
{'W2': array([[-0.99656534, -0.0291583 ,  0.27362312,  0.85685396, -0.288289  ,
        -0.78383398,  0.41722696, -0.36665639, -0.94868803,  0.5635501 ],
       [ 0.65278481, -0.92997819,  0.47758893,  0.4613792 ,  0.82786383,
         1.00139893,  0.5132631 ,  0.41194329,  0.84236233, -0.42041361],
       [ 0.720952  , -0.16571122, -0.61105809,  0.13080033, -0.42074204,
        -0.23679621,  0.15344648, -0.98942997,  0.11656082,  0.18263149],
       [ 0

In [ ]:
coefficients = [random.uniform(-1, 1) for _ in range(10)]
def polynomial(X):
    x = X[0]
    result = sum(
        coefficients[i]*x**i
        for i in range(10)
    )
    return np.array([result])

complex_mathematical_function_experiment(
    function=polynomial,
    input_neurons=1,
    output_neurons=1,
    random_x_generator= lambda: random.uniform(-10, 10),
    hidden_layers=4,
    neurons_per_hidden_layer=10,
    epochs=20,
    learning_rate=10**-4
)

3.334399902288701e+16
Parameters of network
{'W1': array([[-103.94643444],
       [-928.46176283],
       [  38.58359977],
       [  14.93198346],
       [ 136.88349599],
       [ -15.12756174],
       [ -38.04405694],
       [  37.27344988],
       [ -85.47113308],
       [  55.25004604]])}
{'B1': array([  8.71810716, -94.77411351,  -5.02707505, -24.18040157,
       -14.67144544,   9.28587638, -36.60329994,  -3.81151203,
       -12.75633944,  -3.72147446])}
{'W2': array([[ -0.98802522,   0.42905777,  -0.66801885,   1.57875617,
          0.74616094,  -1.41459159,  -5.71679553,  -0.03933153,
         -0.60728857,   0.97578554],
       [ -0.04280951,  -0.96165479,   0.11832701,  -0.59664139,
         -0.32016336,   0.3292144 ,   3.02099164,   0.27880595,
          0.26307068,  -1.5617449 ],
       [ 16.52942064,  -3.39167586,  -6.39990724,   1.24514889,
         11.39901969,   4.24793422,   1.74686134,   4.78495963,
         -1.38773846,   1.1572887 ],
       [ -0.05037074,  -1.49871656,

In [ ]:
def area_under_polynomial(X):
    # this find the area under some polynomial given by a set of coefficients withing an inerval [a, b]
    a, b, coefficients = X[0], X[1], X[2:]
    
    antideriavitve = lambda x: sum(
        coefficients[i]*i*x**(i-1)
        for i in range(1, 10)
    )

    integral = antideriavitve(a) - antideriavitve(b) 
    return np.array([integral])

model_integrate = complex_mathematical_function_experiment(
    function=area_under_polynomial,
    input_neurons=12,
    output_neurons=1,
    random_x_generator= lambda: random.uniform(-10, 10),
    hidden_layers=4,
    neurons_per_hidden_layer=10,
    epochs=20,
    learning_rate=10**-4
)

2.1909708833412882e+18
Parameters of network
{'W1': array([[-3.42435081e+03,  6.20589985e+03,  5.24664565e+03,
        -3.31644773e+03, -1.01306892e+04,  3.30148138e+03,
        -1.36195433e+04, -8.17296306e+03,  9.31025815e+03,
        -9.26415117e+03, -1.59138959e+04, -2.86481845e+02],
       [ 6.90868680e+02,  4.37287117e+02,  4.01278431e+02,
         1.58047271e+02, -4.08040017e+02,  3.95926061e+02,
         5.39872022e+02, -4.86699057e+01,  3.70689019e+02,
         6.17220469e+01, -1.42281162e+02, -9.97819215e+01],
       [ 3.26573267e+02,  4.85583280e+02, -5.57248031e+01,
         4.24779321e+02, -2.54115074e+02,  2.86803779e+02,
        -5.28479806e+01, -5.97558282e+02, -1.70677935e+02,
         2.89607385e+02, -2.23927139e+02, -3.45059606e+02],
       [-1.50334357e+02,  3.13117337e+02, -2.52817286e+02,
         1.76732034e+01, -9.54030555e+01, -1.03988684e+02,
        -1.14339851e+02, -7.29703572e+01,  2.18701227e+02,
        -7.08330829e+01, -5.98659200e+01,  3.45379990e+02],


In [ ]:
model_integrate.FFN.foreward_propagate(
    np.array([0, 5, 3, 2, 5] + 7*[0])
)

(array([61929645.58740462]), None)