In [1]:
from machine_learning_functions import *
from itertools import product
import random

In [2]:
def experiment_linear(a, b, learning_rate, epochs, random_x_function):
    a, b = float(a), float(b)
    model = Model(
        FFN = FFN(
            neurons_per_layer_list=[1, 1],
            activation_functions_list=[None,],
            cost_function=MSE()
        ),
        data_set=create_1_input_1_output_XY_data(
            function=lambda x: a*x+b,
            num_data_items=10000,
            random_x_function=random_x_function
        )
    )
    mean_cost, variance_cost = model.train_and_evaluate(
        learning_rate=learning_rate,
        epochs=epochs,
        batch_size=50
    )
    print(f"Experiment results were:   mean_cost={mean_cost:.4f}   with   variance={variance_cost:.4f}")

    model.print_FFN_parameters()
    return model

In [3]:
def experiment_generator_factory_linear(coefficients, epochs_set, learning_rate_set, x_intervals):
    for (a, b), learning_rate, epochs, x_interval in product(coefficients, learning_rate_set, epochs_set, x_intervals):
        parameters = {
            "coefficients": (a, b),
            "learning_rate": learning_rate,
            "epochs": epochs,
            "x_interval": x_interval,
        }
        def experiment():
            experiment_linear(
                a=a, b=b, 
                learning_rate=learning_rate, 
                epochs=epochs, 
                random_x_function=lambda: random.uniform(*x_interval)
            )
        yield experiment, parameters


In [4]:
experiemnt_generator = experiment_generator_factory_linear(
    coefficients=(
        (2, 5),
        (-10, 6),
        (1/2, -5/4),
        (100, -50),
        (1/100, 20)
    ),
    epochs_set=(
        # 1, 5, 10, 20,
        5,
    ),
    learning_rate_set=(
        # 10**-2, 10**-3, 10**-4, 10**-5
        10**-2, 10**-3, 10**-4,
    ),
    x_intervals = (
        (-1, 1),      
        (-10, 10),
        (-100, 100),
    ),
)

for i, (experiment, parameters) in enumerate(experiemnt_generator):
    print(f"Experiment {i} with parameters:")
    print(parameters)
    experiment()
    print("\n")

Experiment 0 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1)}
Experiment results were:   mean_cost=0.0352   with   variance=0.0011
Parameters of network
{'W1': array([[1.6817033]])}
{'B1': array([4.96075779])}


Experiment 1 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-10, 10)}
Experiment results were:   mean_cost=0.0019   with   variance=0.0000
Parameters of network
{'W1': array([[1.9997823]])}
{'B1': array([4.9561862])}


Experiment 2 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-100, 100)}


c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:331: RuntimeWarning: overflow encountered in scalar add
  total_cost += cost
c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:154: RuntimeWarning: overflow encountered in matmul
  dcdAp = dZdAp.T @ dcdZ
c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:342: RuntimeWarning: invalid value encountered in scalar subtract
  loss_change = new_loss - old_loss
c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:338: RuntimeWarning: overflow encountered in add
  total_param_cost_gradients[param_name] += param_gradients[param_name]
c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:338: RuntimeWarning: invalid value encountered in add
  total_param_cost_gradients[param_name] += param

Experiment results were:   mean_cost=nan   with   variance=nan
Parameters of network
{'W1': array([[nan]])}
{'B1': array([nan])}


Experiment 3 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.001, 'epochs': 5, 'x_interval': (-1, 1)}
Experiment results were:   mean_cost=11.7296   with   variance=64.0723
Parameters of network
{'W1': array([[-0.17097378]])}
{'B1': array([1.88670581])}


Experiment 4 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.001, 'epochs': 5, 'x_interval': (-10, 10)}
Experiment results were:   mean_cost=9.7853   with   variance=0.0025
Parameters of network
{'W1': array([[1.99864053]])}
{'B1': array([1.87294099])}


Experiment 5 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.001, 'epochs': 5, 'x_interval': (-100, 100)}
Experiment results were:   mean_cost=inf   with   variance=nan
Parameters of network
{'W1': array([[-8.5908801e+173]])}
{'B1': array([-4.16322796e+171])}


Experiment 6 with parameters:
{'coefficients': (2, 5), 'l

c:\Users\Henry\Documents\compsci presentations\machine learning library 1\machine_learning_functions.py:386: RuntimeWarning: invalid value encountered in scalar subtract
  (sum(cost**2 for cost in costs) / self.num_test_data_items)


Experiment results were:   mean_cost=23.8632   with   variance=121.6089
Parameters of network
{'W1': array([[0.10221544]])}
{'B1': array([0.23100418])}


Experiment 7 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.0001, 'epochs': 5, 'x_interval': (-10, 10)}
Experiment results were:   mean_cost=24.4965   with   variance=256.0182
Parameters of network
{'W1': array([[1.72456855]])}
{'B1': array([0.22839594])}


Experiment 8 with parameters:
{'coefficients': (2, 5), 'learning_rate': 0.0001, 'epochs': 5, 'x_interval': (-100, 100)}
Experiment results were:   mean_cost=22.8950   with   variance=5.6721
Parameters of network
{'W1': array([[1.99564155]])}
{'B1': array([0.22477958])}


Experiment 9 with parameters:
{'coefficients': (-10, 6), 'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1)}
Experiment results were:   mean_cost=1.1095   with   variance=1.2109
Parameters of network
{'W1': array([[-8.03492778]])}
{'B1': array([6.0774623])}


Experiment 10 with parameters:
{'co

c:\Users\Henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\numeric.py:925: RuntimeWarning: overflow encountered in multiply
  return multiply(a.ravel()[:, newaxis], b.ravel()[newaxis, :], out)


Experiment results were:   mean_cost=3817.0253   with   variance=15244382.2093
Parameters of network
{'W1': array([[15.67840185]])}
{'B1': array([-19.29299329])}


Experiment 31 with parameters:
{'coefficients': (100, -50), 'learning_rate': 0.001, 'epochs': 5, 'x_interval': (-10, 10)}
Experiment results were:   mean_cost=941.3190   with   variance=2764.3648
Parameters of network
{'W1': array([[100.14853094]])}
{'B1': array([-19.29171494])}


Experiment 32 with parameters:
{'coefficients': (100, -50), 'learning_rate': 0.001, 'epochs': 5, 'x_interval': (-100, 100)}
Experiment results were:   mean_cost=inf   with   variance=nan
Parameters of network
{'W1': array([[-3.00773978e+173]])}
{'B1': array([-5.93624267e+170])}


Experiment 33 with parameters:
{'coefficients': (100, -50), 'learning_rate': 0.0001, 'epochs': 5, 'x_interval': (-1, 1)}
Experiment results were:   mean_cost=5598.0319   with   variance=37723461.8875
Parameters of network
{'W1': array([[1.75803752]])}
{'B1': array([-2.2947

In [5]:
def experiment_learn_FFN(learning_rate, epochs, random_x_function, neurons_per_layer_list, activation_functions_list, cost_function):
    target_FFN = FFN(
        neurons_per_layer_list=neurons_per_layer_list,
        activation_functions_list=activation_functions_list,
        cost_function=cost_function
    )

    data_set = create_a_inputs_b_outputs_XY_data(
        a=neurons_per_layer_list[0], 
        b=neurons_per_layer_list[-1],
        num_data_items=10_000,
        random_x_function= random_x_function,
        function= lambda X: target_FFN.foreward_propagate(X)[0]
    )


    model_to_train = FFN(
        neurons_per_layer_list=neurons_per_layer_list,
        activation_functions_list=activation_functions_list,
        cost_function=cost_function
    )

    model = Model(
        FFN=model_to_train,
        data_set=data_set
    )
    mean_cost, variance_cost = model.train_and_evaluate(
        learning_rate=learning_rate,
        epochs=epochs,
        batch_size=50
    )
    
    print(f"Experiment results were:   mean_cost={mean_cost:.4f}   with   variance={variance_cost:.4f}")

    # model.print_FFN_parameters()

    return (model, target_FFN)

In [6]:
def experiment_generator_factory_FFN(
        learning_rates, epochs_sets, x_intervals, neurons_and_activation_layer_lists, cost_functions
):
    for learning_rate, epochs, x_interval, (neurons_per_layer_list, activation_functions_list), cost_function in product(
        learning_rates, epochs_sets, x_intervals, neurons_and_activation_layer_lists, cost_functions
    ):
        parameters = {
            "learning_rate": learning_rate,
            "epochs": epochs,
            "x_interval": x_interval,
            "neurons_per_layer_list": neurons_per_layer_list,
            "activation_functions_list": [type(activation).__name__ for activation in activation_functions_list],
            "cost_function": type(cost_function).__name__,
        }
        def experiment():
            return experiment_learn_FFN(
                learning_rate=learning_rate, 
                epochs=epochs,
                random_x_function=lambda: random.uniform(*x_interval),
                neurons_per_layer_list=neurons_per_layer_list, 
                activation_functions_list=activation_functions_list,
                cost_function=cost_function
            )
        yield experiment, parameters


In [7]:
experiemnt_generator = experiment_generator_factory_FFN(
    neurons_and_activation_layer_lists=(
        (
            [5, 5, 5, 5],
            [Sigmoid(), Sigmoid(), None]
        ),
        (
            [1, 10, 1],
            [RELU(), Sigmoid()]
        ),
        (
            [10, 20, 20, 10],
            [RELU(), RELU(), Sigmoid()]
        ),
        (
            [1, 1],
            [None]
        )
    ),
    cost_functions=(
        MSE(),
    ),
    epochs_sets=(
        # 5, 10, 20,
        5,
    ),
    learning_rates=(
        10**-i for i in range(2, 5)
    ),
    x_intervals = (
        (-1, 1),      
        (0, 1),
        (-10, 10),
    ),
)

trained_models = []
traget_FFNs = []
for i, (experiment, parameters) in enumerate(experiemnt_generator):
    print(f"Experiment {i} with parameters:")
    print(parameters)
    trained_model, traget_FFN = experiment()
    trained_models.append(trained_model)
    traget_FFNs.append(traget_FFN)
    # model[i].print_parameters()
    print("\n")

Experiment 0 with parameters:
{'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1), 'neurons_per_layer_list': [5, 5, 5, 5], 'activation_functions_list': ['Sigmoid', 'Sigmoid', 'NoneType'], 'cost_function': 'MSE'}
Experiment results were:   mean_cost=16.8693   with   variance=187596.7802


Experiment 1 with parameters:
{'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1), 'neurons_per_layer_list': [1, 10, 1], 'activation_functions_list': ['RELU', 'Sigmoid'], 'cost_function': 'MSE'}
Experiment results were:   mean_cost=0.0006   with   variance=0.0000


Experiment 2 with parameters:
{'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1), 'neurons_per_layer_list': [10, 20, 20, 10], 'activation_functions_list': ['RELU', 'RELU', 'Sigmoid'], 'cost_function': 'MSE'}
Experiment results were:   mean_cost=12.7590   with   variance=215239.4861


Experiment 3 with parameters:
{'learning_rate': 0.01, 'epochs': 5, 'x_interval': (-1, 1), 'neurons_per_layer_list': [1, 1], 'activation_fu

In [8]:
# check result of experiment that supposedly went well

experiment_index = 4
x_range = (0, 1)

X = np.array([random.uniform(*x_range) for _ in range(5)])
Y, _ = traget_FFNs[experiment_index].foreward_propagate(X)
P, _ = trained_models[experiment_index].FFN.foreward_propagate(X)
cost = MSE()(P, Y)

print(X)
print(Y)
print(P)
print(cost)

[0.6994899  0.4040818  0.2370441  0.77315645 0.84399654]
[ 0.02420778 -0.11349925  0.00229938 -0.06468189  0.15571875]
[-0.60059206  0.22659928 -1.07501149  1.07400259 -0.63878825]
0.71889685798548


In [9]:
print(traget_FFNs[experiment_index].tranformation_layers[2].bias)
print(traget_FFNs[experiment_index].tranformation_layers[2].bias)

print(
    traget_FFNs[experiment_index].tranformation_layers[2].bias - traget_FFNs[experiment_index].tranformation_layers[2].bias
)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [10]:
for i in range(3):
      print(
            traget_FFNs[experiment_index].tranformation_layers[i].weights
            -
            traget_FFNs[experiment_index].tranformation_layers[i].weights
      )
      print(
            traget_FFNs[experiment_index].tranformation_layers[i].bias
            -
            traget_FFNs[experiment_index].tranformation_layers[i].bias
      )


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
