In [1]:
# imports
from machine_learning_functions import *

In [2]:
(X := np.array([0.5, 1.0, 10.0, -5.0, -0.1, 0.0, -1.0, -0.3, 0.6, 0.4]))

array([ 0.5,  1. , 10. , -5. , -0.1,  0. , -1. , -0.3,  0.6,  0.4])

In [3]:
sigmoid = Sigmoid()

In [4]:
sigmoid(X)

array([ 0.04843825,  0.03301454,  0.00490444, -0.01170297,  0.11024104,
        0.09090909, -0.12063188,  0.19182462,  0.04429912,  0.05343058])

In [5]:
sigmoid.dX(X)

array([[ 0.04609199,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.03192458,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00488039,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.01183993,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.09808796,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.08264463,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.13518393,  0.        

In [6]:
sigmoid.dX(X).shape

(10, 10)

In [7]:
# activation = RELU()
activation = Leaky_RELU(0.2)

In [8]:
activation(X)

array([ 0.5 ,  1.  , 10.  , -1.  , -0.02,  0.  , -0.2 , -0.06,  0.6 ,
        0.4 ])

In [9]:
activation.vectorised_derivative(X)

array([1. , 1. , 1. , 0.2, 0.2, 1. , 0.2, 0.2, 1. , 1. ])

In [10]:
activation.dX(X)

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 1. ]])

Test the layer class

In [11]:
layer = Layer_Transformation(4, 2, RELU())

In [12]:
layer.weights

array([[-0.09064785, -0.79155874],
       [-0.44657293, -0.2488978 ],
       [-0.51476828,  0.60746217],
       [ 0.5473846 , -0.99528016]])

In [13]:
layer.bias

array([0.5, 0.5, 0.5, 0.5])

In [14]:
layer.get_activations(
    np.array([0,0])
)

array([0.5, 0.5, 0.5, 0.5])

In [15]:
layer.get_activations(
    np.array([1,1])
)

array([-0.        , -0.        ,  0.59269389,  0.05210445])

In [16]:
layer.get_activations(
    np.array([0.34,0.81])
)

array([-0.        ,  0.14655799,  0.81702314, -0.        ])

In [17]:
layer.weighted_sums

array([-0.17198285,  0.14655799,  0.81702314, -0.12006616])

In [18]:
layer.activations

array([-0.        ,  0.14655799,  0.81702314, -0.        ])

In [19]:
(
    layer.dAdZ(),
    layer.dZdW(),
    layer.dZdAp()
)


(array([[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]]),
 array([0.34, 0.81]),
 array([[-0.09064785, -0.79155874],
        [-0.44657293, -0.2488978 ],
        [-0.51476828,  0.60746217],
        [ 0.5473846 , -0.99528016]]))

In [20]:
cost_func = MSE()
cost_func(
    layer.activations,
    np.array([0, 0, 1, 0])
)

0.013739943763856552

In [21]:
(
    (dAdZ := layer.dAdZ()),
    (dcdA := cost_func.dP()),
    (dcdZ := dAdZ @ dcdA)   
)

(array([[0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]]),
 array([-0.        ,  0.07327899, -0.09148843, -0.        ]),
 array([ 0.        ,  0.07327899, -0.09148843,  0.        ]))

In [22]:
# here I will use outer product rather than transverses
(
    dcdZ,
    (dZdW := layer.dZdW()),
    (dcdW := np.outer(dcdZ, dZdW))
)

(array([ 0.        ,  0.07327899, -0.09148843,  0.        ]),
 array([0.34, 0.81]),
 array([[ 0.        ,  0.        ],
        [ 0.02491486,  0.05935599],
        [-0.03110607, -0.07410563],
        [ 0.        ,  0.        ]]))

In [23]:
# (
#     (dZdB := layer.dZdB()),
#     dcdZ,
#     (dcdB := dZdB @ dcdZ)
# )

(
    dcdZ,
    (dcdB := dcdZ)
)

(array([ 0.        ,  0.07327899, -0.09148843,  0.        ]),
 array([ 0.        ,  0.07327899, -0.09148843,  0.        ]))

In [24]:
(
    (dZdAp := layer.dZdAp()),
    dcdZ,
    (dcdAp := dZdAp.T @ dcdZ)
)

(array([[-0.09064785, -0.79155874],
        [-0.44657293, -0.2488978 ],
        [-0.51476828,  0.60746217],
        [ 0.5473846 , -0.99528016]]),
 array([ 0.        ,  0.07327899, -0.09148843,  0.        ]),
 array([ 0.01437093, -0.07381474]))

In [25]:
model = FFN(
    [2,4,2],
    [RELU() for _ in range(2)],
    MSE()
)

In [26]:
(
    model.tranformation_layers[0].weights,
    model.tranformation_layers[0].bias,
    model.tranformation_layers[1].weights,
    model.tranformation_layers[1].bias
)

(array([[-0.55816015,  0.2858176 ],
        [-0.21456866, -0.57383174],
        [-0.43776862, -0.84339484],
        [ 0.80917179,  0.88996469]]),
 array([0.5, 0.5, 0.5, 0.5]),
 array([[-0.35003769,  0.9576626 , -0.8890226 ,  0.16348804],
        [-0.20132945,  0.35412975,  0.50686099,  0.80956816]]),
 array([0.5, 0.5]))

In [27]:
model.foreward_propagate(
    np.array([0, 0]),
    np.array([1, 1])
)

(array([0.44104518, 1.23461473]), 0.18373728297811864)

In [28]:
model.back_propogate(
    np.array([0, 0]),
    np.array([1, 1])
)

{'W2': array([[-0.27947741, -0.27947741, -0.27947741, -0.27947741],
        [ 0.11730736,  0.11730736,  0.11730736,  0.11730736]]),
 'B2': array([-0.55895482,  0.23461473]),
 'W1': array([[ 0.,  0.],
        [-0., -0.],
        [ 0.,  0.],
        [ 0.,  0.]]),
 'B1': array([ 0.1484204 , -0.45220608,  0.61584053,  0.09855418])}

In [29]:
from random import uniform

In [30]:
# # create random function to learn
# degree = 1
# coefficients = [uniform(-1, 1) for _ in range(degree+1)]

# def polynomial_function(x):
#     return sum(coefficients[i] * x**i for i in range(degree+1))

def linear_function(x): return 2*x+5

In [31]:
num_data_items = 1000
X_data = [uniform(-100, 100) for _ in range(num_data_items)]
Y_data = [linear_function(X_data[i]) for i in range(num_data_items)]

X_data, Y_data = np.array(X_data), np.array(Y_data)

In [32]:
function_emulator_model = FFN(
    [1, 1],
    [Linear_Activation_Funcion()],
    MSE()
)

In [33]:
(
    function_emulator_model.tranformation_layers[0].weights,
    function_emulator_model.tranformation_layers[0].bias,
)

(array([[0.51662746]]), array([0.5]))

In [34]:
# function_emulator_model.transformation_layers[0].weights = np.array([[2.0]])
# function_emulator_model.transformation_layers[0].bias = np.array([5.0])

In [35]:
# function_emulator_model.transformation_layers[0].weights = np.array([[1.2]])
# function_emulator_model.transformation_layers[0].bias = np.array([3.0])

In [36]:
function_emulator_model.foreward_propagate(2, 2*2+5)

(array([1.53325493]), 55.75228194202673)

In [37]:
function_emulator_model.back_propogate(2, 2*2+5)

{'W1': array([[-29.86698028]]), 'B1': array([-14.93349014])}

In [38]:
function_emulator_model.foreward_propagate(-3, (-3)*2+5)

(array([-1.04988239]), 0.0024882533143272354)

In [39]:
function_emulator_model.back_propogate(-3, (-3)*2+5)

{'W1': array([[0.29929437]]), 'B1': array([-0.09976479])}

In [40]:
training_manager = Model(
    FFN=function_emulator_model,
    data_set=(X_data, Y_data)
)

In [41]:
training_manager.train_and_evaluate(
    learning_rate=0.0001,
    epochs=10,
    batch_size=50
)

14.35824670325447

In [42]:
(
    function_emulator_model.tranformation_layers[0].weights,
    function_emulator_model.tranformation_layers[0].bias,
)

(array([[1.99942258]]), array([1.21192484]))

In [43]:
for _ in range(10):
    x = uniform(-1, 1)
    y = linear_function(x)
    p, c = training_manager.FFN.foreward_propagate(
        np.array([x,]), np.array([y,])
    )
    print(f"For the input {x:.4f} the network predicted {p[0]:.4f} and actual value was {y:.4f} giving a cost of {c:.4f}")

For the input 0.8926 the network predicted 2.9967 and actual value was 6.7853 giving a cost of 14.3534
For the input -0.8759 the network predicted -0.5393 and actual value was 3.2482 giving a cost of 14.3457
For the input -0.0286 the network predicted 1.1548 and actual value was 4.9428 giving a cost of 14.3494
For the input -0.8426 the network predicted -0.4728 and actual value was 3.3147 giving a cost of 14.3458
For the input 0.8849 the network predicted 2.9812 and actual value was 6.7698 giving a cost of 14.3534
For the input -0.6873 the network predicted -0.1622 and actual value was 3.6255 giving a cost of 14.3465
For the input 0.1227 the network predicted 1.4573 and actual value was 5.2455 giving a cost of 14.3501
For the input 0.0584 the network predicted 1.3287 and actual value was 5.1168 giving a cost of 14.3498
For the input 0.0623 the network predicted 1.3364 and actual value was 5.1245 giving a cost of 14.3498
For the input -0.9207 the network predicted -0.6290 and actual val

In [44]:
# create random function to learn
degree = 1
coefficients = [uniform(-1, 1) for _ in range(degree+1)]

def polynomial_function(x):
    return sum(coefficients[i] * x**i for i in range(degree+1))

In [45]:
coefficients

[0.35074834378407993, -0.6476307797195384]

In [46]:
num_data_items = 10000
X_data = [uniform(-100, 100) for _ in range(num_data_items)]
Y_data = [linear_function(X_data[i]) for i in range(num_data_items)]

X_data, Y_data = np.array(X_data), np.array(Y_data)

In [47]:
function_emulator_model = FFN(
    [1, 1, 1],
    [Leaky_RELU(0.01), Linear_Activation_Funcion()],
    MSE()
)

# function_emulator_model = FFN(
#     [1, 1],
#     [Linear_Activation_Funcion()],
#     MSE()
# )

In [48]:
(
    function_emulator_model.tranformation_layers[0].weights,
    function_emulator_model.tranformation_layers[0].bias,
)

(array([[-0.33452972]]), array([0.5]))

In [49]:
training_manager = Model(
    FFN=function_emulator_model,
    data_set=(X_data, Y_data)
)

In [50]:
training_manager.train_and_evaluate(
    learning_rate=0.0001,
    epochs=10,
    batch_size=50
)

2849.3752604979236

In [51]:
(
    function_emulator_model.tranformation_layers[0].weights,
    function_emulator_model.tranformation_layers[0].bias,
    function_emulator_model.tranformation_layers[1].weights,
    function_emulator_model.tranformation_layers[1].bias,
)

(array([[1.29304125]]),
 array([11.45175091]),
 array([[2.14321746]]),
 array([-51.47822236]))

In [52]:
for _ in range(10):
    x = uniform(-1, 1)
    y = linear_function(x)
    p, c = training_manager.FFN.foreward_propagate(
        np.array([x,]), np.array([y,])
    )
    print(f"For the input {x:.4f} the network predicted {p[0]:.4f} and actual value was {y:.4f} giving a cost of {c:.4f}")

For the input -0.8135 the network predicted -29.1891 and actual value was 3.3730 giving a cost of 1060.2882
For the input -0.7973 the network predicted -29.1441 and actual value was 3.4054 giving a cost of 1059.4733
For the input -0.1669 the network predicted -27.3971 and actual value was 4.6663 giving a cost of 1028.0572
For the input 0.2831 the network predicted -26.1502 and actual value was 5.5661 giving a cost of 1005.9251
For the input 0.7605 the network predicted -24.8272 and actual value was 6.5209 giving a cost of 982.7036
For the input -0.5839 the network predicted -28.5528 and actual value was 3.8322 giving a cost of 1048.7863
For the input -0.4445 the network predicted -28.1665 and actual value was 4.1110 giving a cost of 1041.8343
For the input -0.1829 the network predicted -27.4416 and actual value was 4.6341 giving a cost of 1028.8516
For the input 0.9026 the network predicted -24.4332 and actual value was 6.8053 giving a cost of 975.8413
For the input 0.2418 the network 