In [1]:
from activation_functions import *
from ml_exceptions import ObjectNotCompiledEror, ObjectCompiliationError

In [2]:
relu = RELU()

In [3]:
try:
    relu.compute_activation(None)
except ObjectNotCompiledEror:
    pass

In [4]:
try:
    relu.compile()
except ObjectCompiliationError:
    pass

In [5]:
relu_batch_size = 5
relu_vector_size = 3

In [6]:
relu\
    .set_batch_size(relu_batch_size)\
    .set_vector_size(relu_vector_size)\
    .compile()

In [7]:
X = np.random.uniform(-5, 5, size=(3,5))

In [8]:
relu.compute_activation(X)

array([[-0.        , -0.        , -0.        , -0.        ,  3.32996356],
       [-0.        ,  3.96577691, -0.        , -0.        , -0.        ],
       [ 4.23780773,  2.49725289,  2.11668512, -0.        ,  2.7733116 ]])

In [9]:
relu.compute_activation_gradient()

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]]])

In [10]:
relu.compute_activation_gradient()

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]]])

In [11]:

try:
    relu\
        .set_batch_size(10)\
        .compute_activation_gradient()
except ObjectNotCompiledEror:
    pass

In [12]:
relu\
    .set_batch_size(relu_batch_size)\
    .compile()\
    .compute_activation_gradient()

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.]]])

In [13]:
# non_activation = Identity_Function(
#     batch_size=5,
#     vector_size=3
# )

non_activation = Identity_Function()\
    .set_batch_size(5)\
    .set_vector_size(3)\
    .compile()

In [14]:
X = np.random.uniform(-1, 1, (3,5))
X

array([[ 0.86946787,  0.24718466, -0.68548872, -0.20994345, -0.07647977],
       [-0.50922438,  0.10201213,  0.71886933, -0.1340751 ,  0.63919651],
       [ 0.70114614,  0.42855046, -0.10459736, -0.46819464, -0.74615566]])

In [15]:
non_activation.compute_activation(X)

array([[ 0.86946787,  0.24718466, -0.68548872, -0.20994345, -0.07647977],
       [-0.50922438,  0.10201213,  0.71886933, -0.1340751 ,  0.63919651],
       [ 0.70114614,  0.42855046, -0.10459736, -0.46819464, -0.74615566]])

In [16]:
non_activation.compute_activation_gradient()

array([[[1., 0., 0., 0., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 0., 1., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 1., 0., 0.]],

       [[0., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 0., 0., 0., 1.]]])

In [17]:
tanh_activation = TANH()\
    .set_batch_size(5)\
    .set_vector_size(3)\
    .compile()

In [25]:
X = np.random.uniform(-3, 3, (3,5))

In [26]:
tanh_activation.compute_activation(X)

array([[ 0.80893695,  0.62147778,  0.82606176, -0.94984673, -0.98995922],
       [-0.73080407, -0.72777588, -0.74228637, -0.00911319,  0.67052311],
       [ 0.95805763,  0.86347897,  0.97936095, -0.91629036, -0.93999483]])

In [27]:
tanh_activation.compute_activation_gradient()

array([[[0.34562101, 0.        , 0.        , 0.        , 0.46592541],
        [0.        , 0.        , 0.        , 0.08212558, 0.61376537],
        [0.        , 0.        , 0.        , 0.47034227, 0.        ]],

       [[0.        , 0.        , 0.25440407, 0.31762198, 0.        ],
        [0.        , 0.        , 0.44901095, 0.        , 0.        ],
        [0.        , 0.04085214, 0.0977912 , 0.        , 0.        ]],

       [[0.        , 0.99991695, 0.        , 0.        , 0.        ],
        [0.16041198, 0.01998075, 0.        , 0.        , 0.        ],
        [0.55039876, 0.        , 0.        , 0.        , 0.11640972]]])