In [1]:
from loss_functions import *
from ml_exceptions import ObjectNotCompiledEror, ObjectCompiliationError

In [2]:
MC_MSE = MC_MSE()

In [3]:
try:
    MC_MSE.compute_loss(None, None)
except ObjectNotCompiledEror:
    pass

In [4]:
try:
    MC_MSE.compile()
except ObjectCompiliationError:
    pass

In [5]:
MC_MSE_batch_size = 10
MC_MSE_vector_size = 5

In [6]:
MC_MSE\
    .set_batch_size(MC_MSE_batch_size)\
    .set_vector_size(MC_MSE_vector_size)\
    .compile()

In [7]:
(
    (Y := np.random.uniform(-5, 5, (MC_MSE_vector_size, MC_MSE_batch_size))),
    (P := np.random.uniform(-5, 5, (MC_MSE_vector_size, MC_MSE_batch_size)))
)


(array([[-1.20536634, -3.75892718,  0.27993731,  4.95846832, -0.69614271,
         -3.81538403,  2.65198536, -3.76851471,  0.89203593,  0.59563047],
        [ 0.40255126, -0.41214259,  0.1344483 , -4.05928924,  0.15713677,
         -4.33739095,  4.54531003,  4.33895372,  2.7406587 , -3.37214945],
        [-3.72507613, -1.17560386, -4.82266297,  2.19122439,  1.28967707,
         -2.60936015, -1.39147829, -2.05633822, -3.81059671,  4.89495525],
        [-2.76236443,  3.34193258, -1.16278039,  3.76701039, -0.48354474,
          0.67102552, -2.5045858 ,  4.01157828, -4.20947247, -0.01114582],
        [-2.60689623,  2.84704769,  1.08233953, -3.52431091, -2.30344579,
         -2.68015324,  3.1156936 , -3.86337001, -3.89482438,  1.8603491 ]]),
 array([[ 4.8608049 , -0.27069931,  3.55830807, -2.74981564,  3.49715369,
         -0.26918137, -4.98348954, -3.87898852, -0.21046794, -1.08867773],
        [-3.84758114,  2.53771787,  2.04284433, -4.26134236,  4.08629939,
         -3.89601724, -0.67458

In [8]:
MC_MSE.compute_loss(P, Y)

17.84619181953761

In [9]:
MC_MSE.compute_loss_gradient()

array([[ 0.24264685,  0.13952911,  0.13113483, -0.30833136,  0.16773186,
         0.14184811, -0.305419  , -0.00441895, -0.04410016, -0.06737233],
       [-0.1700053 ,  0.11799442,  0.07633584, -0.00808213,  0.15716651,
         0.01765495, -0.20879586, -0.08728741,  0.09007869,  0.12355363],
       [ 0.16822114, -0.02474461,  0.27430699, -0.24379315,  0.10084173,
         0.0275766 , -0.06626846,  0.26087577,  0.1061182 , -0.22938707],
       [-0.08853187, -0.17428585, -0.07926439, -0.10496598,  0.02735421,
        -0.02829869, -0.0396874 , -0.20652559,  0.33195978, -0.17945473],
       [ 0.12076526, -0.23011744,  0.14971874,  0.33115336, -0.03078316,
         0.29843404, -0.14064356,  0.14640588,  0.13821548, -0.19035872]])

In [10]:
try:
    MC_MSE\
        .set_batch_size(10)\
        .compute_loss_gradient()
except ObjectNotCompiledEror:
    pass

In [11]:
MC_MSE\
    .set_batch_size(MC_MSE_batch_size)\
    .compile()\
    .compute_loss_gradient()


array([[ 0.24264685,  0.13952911,  0.13113483, -0.30833136,  0.16773186,
         0.14184811, -0.305419  , -0.00441895, -0.04410016, -0.06737233],
       [-0.1700053 ,  0.11799442,  0.07633584, -0.00808213,  0.15716651,
         0.01765495, -0.20879586, -0.08728741,  0.09007869,  0.12355363],
       [ 0.16822114, -0.02474461,  0.27430699, -0.24379315,  0.10084173,
         0.0275766 , -0.06626846,  0.26087577,  0.1061182 , -0.22938707],
       [-0.08853187, -0.17428585, -0.07926439, -0.10496598,  0.02735421,
        -0.02829869, -0.0396874 , -0.20652559,  0.33195978, -0.17945473],
       [ 0.12076526, -0.23011744,  0.14971874,  0.33115336, -0.03078316,
         0.29843404, -0.14064356,  0.14640588,  0.13821548, -0.19035872]])

In [12]:
loss = MC_MSE.compute_loss(
    P=np.zeros((MC_MSE_vector_size, MC_MSE_batch_size)),
    Y=np.ones((MC_MSE_vector_size, MC_MSE_batch_size))
)
print(loss)
assert round(loss, 12) == 1

1.0
